### ISSUE TITLE
req.param(name) is deprecated

### ISSUE THREAD

**Issue by ksmithut** [73rhodes/passport-opentoken#4]
On this line: https://github.com/73rhodes/passport-opentoken/blob/master/lib/passport-opentoken/strategy.js#L92 it's using req.param(), which is deprecated. 

The deprecation warning I get:

```
Mon, 10 Sep 2018 17:35:21 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at node_modules/passport-opentoken/lib/passport-opentoken/strategy.js:92:19
```

I'm happy to submit a PR if I get any sort of response from the maintainer.

**Comment by 73rhodes** [comment]
Go for it. :-D I'd vote for req.params[tokenName]

**Comment by ksmithut** [comment]
Would it make sense to pass an option to get the param? Something like:

```js
passport.use(new Strategy(
  {
    getToken: req => req.params[tokenName],
    password: '...',
    cipherSuite: 2
  },
  function (subject, cb) {
    cb(subject)
  }
))
```

At least for my use case, the token doesn't come in on one of the path parameters (req.params), it comes in the body. The PR I submitted maintains the same "fallthrough" functionality that express does with `req.param(name)` where first it checks for `req.params[name]`, then `req.body[name]`, then `req.query[name]`, but I'd be fine putting in the "token getter" option, too. Or both, where the default token getter option uses the "tokenName" option.

**Comment by ksmithut** [comment]
fwiw, this is Express' implementation of `req.param`: https://github.com/expressjs/express/blob/b97faff6e2aa4d34d79485fe4331cb0eec13ad57/lib/request.js#L245-L249

**Comment by 73rhodes** [comment]
I didn't see your PR, but I'll check it out.  TBH I always want to keep things as ruthlessly simple as possible so passing in an option with a function to get the value is probably a bit much for my taste. Express is supposed to put request parameters into `params` wether they are `GET` params on the URL or `POST` params in the body.

**Comment by ksmithut** [comment]
Makes sense, and I just barely submitted the PR, so I wouldn't have expected you to see it.

> Express is supposed to put request parameters into params wether they are GET params on the URL or POST params in the body.

That was definitely the case with express before, but it created some ambiguity and created some security concerns. Here's the discussion on express on the topic 3-4 years ago: https://github.com/expressjs/express/issues/2440. I'm happy to maintain the old contract because I don't see much of an issue, which is what I did in [the PR](https://github.com/73rhodes/passport-opentoken/pull/5). Looks like the DeepScan check failed, although I'm unsure what to do about it...

Anyway, no rush on any of this, I'm happy to keep discussing, or keep making changes to match better what you'd like to be done :)

**Comment by ksmithut** [comment]
Just going through and cleaning up some of my PRs out in the wild, just checking up on this. Again, not in any rush or anything. Let me know if there's anything you'd like me to change.

**Comment by ksmithut** [comment]
Closing
